# Generated by Django 5.0.11 on 2025-05-27 18:04

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('wearable', 'Reloj'), ('notebook', 'Notebook'), ('speaker', 'Speaker')], default='smartphone', max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('ruc', models.IntegerField(blank=True, null=True)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smouu.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('fecha_contratatacion', models.DateField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smouu.ciudad')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='InventarioRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_repuesto', models.CharField(max_length=100)),
                ('cantidad_disponible', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smouu.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.BooleanField(choices=[(0, 'Salida'), (1, 'Entrada')])),
                ('cantidad', models.IntegerField()),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smouu.inventariorepuesto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_reportado', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smouu.cliente')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smouu.dispositivo')),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smouu.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado_reparacion', models.CharField(choices=[('pediente', 'Pendiente'), ('enproceso', 'En Proceso'), ('terminado', 'Terminado')], default='pendiente', max_length=30)),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smouu.empleado')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smouu.ordenreparacion')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre_local', models.CharField(max_length=100)),
                ('contacto', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smouu.categoriaproducto')),
            ],
        ),
        migrations.AddField(
            model_name='inventariorepuesto',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smouu.proveedore'),
        ),
    ]
