# Generated by Django 5.0.11 on 2025-05-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pantalla', 'Cambio de Pantalla'), ('bateria', 'Cambio de Batería'), ('otro', 'Otro Servicio')], max_length=20)),
                ('precio', models.IntegerField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='smouu.dispositivo')),
            ],
        ),
    ]
