# Generated by Django 5.0.11 on 2025-03-28 14:13

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PY', unique=True),
        ),
    ]
