# Generated by Django 5.0.11 on 2025-05-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0002_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenreparacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smouu.servicio'),
        ),
    ]
