# Generated by Django 5.0.11 on 2025-03-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0003_alter_empleado_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='id_ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='id_rol',
            new_name='rol',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
