# Generated by Django 5.0.11 on 2025-03-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0006_dispositivo_alter_empleado_usuario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
