# Generated by Django 5.0.11 on 2025-04-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0007_alter_cliente_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='categoria',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('wearable', 'Reloj'), ('notebook', 'Notebook'), ('speaker', 'Speaker')], default='smartphone', max_length=50),
        ),
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema_reportado', models.TextField()),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('delivered', 'Entregado')], default='pending', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smouu.cliente')),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smouu.dispositivo')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smouu.empleado')),
            ],
        ),
    ]
