# Generated by Django 5.0.11 on 2025-04-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0008_alter_dispositivo_categoria_ordenreparacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenreparacion',
            name='id_empleado',
        ),
    ]
