# Generated by Django 5.0.11 on 2025-05-24 14:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0009_remove_ordenreparacion_id_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre_local', models.CharField(max_length=100)),
                ('contacto', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smouu.categoriaproductos')),
            ],
        ),
    ]
