# Generated by Django 5.0.11 on 2025-05-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0010_categoriaproductos_proveedores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProductos',
            new_name='CategoriaProducto',
        ),
        migrations.RenameModel(
            old_name='Proveedores',
            new_name='Proveedore',
        ),
        migrations.CreateModel(
            name='InventarioRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_repuesto', models.CharField(max_length=100)),
                ('cantidad_disponible', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smouu.categoriaproducto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smouu.proveedore')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.BooleanField()),
                ('cantidad', models.IntegerField()),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smouu.inventariorepuesto')),
            ],
        ),
    ]
