# Generated by Django 5.0.11 on 2025-05-24 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('smouu', '0011_rename_categoriaproductos_categoriaproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='movimientorepuesto',
            name='tipo_movimiento',
            field=models.BooleanField(choices=[(0, 'Salida'), (1, 'Entrada')]),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
