# Generated by Django 5.0.11 on 2025-05-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0012_alter_empleado_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenreparacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='id_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smouu.empleado'),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='fecha_finalizacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proveedore',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smouu.categoriaproducto'),
        ),
    ]
