# Generated by Django 5.0.11 on 2025-05-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0013_remove_ordenreparacion_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenreparacion',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
