# Generated by Django 5.0.11 on 2025-05-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smouu', '0014_alter_ordenreparacion_fecha_finalizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado_reparacion', models.CharField(choices=[('pediente', 'Pendiente'), ('enproceso', 'En Proceso'), ('terminado', 'Terminado')], default='pendiente', max_length=30)),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smouu.empleado')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smouu.ordenreparacion')),
            ],
        ),
    ]
